create database camila;
use camila;
CREATE TABLE VENTAS ( Id_ventas INT PRIMARY KEY, Fecha_venta DATE, Cod_Producto INT, Cantidad INT, Valor_Venta INT);
INSERT INTO VENTAS (Id_ventas, Fecha_venta, Cod_Producto, Cantidad, Valor_Venta) VALUES (1, '2022-11-12', 8901, 5, 5000), (2, '2022-11-12', 7501, 4, 8000), (3, '2022-11-13', 9801, 12, 6000), (4, '2023-11-13', 7501, 6, 12000), (5, '2023-12-05', 8564, 7, 13000);
SELECT * FROM VENTAS;
SELECT Id_ventas FROM VENTAS WHERE Cod_Producto = 9801;
UPDATE VENTAS SET Cantidad = 20, Valor_Venta = 10000 WHERE Id_ventas = 3;
SELECT * FROM VENTAS;
ALTER TABLE VENTAS ADD COLUMN Tipo_Producto VARCHAR(50);
SELECT * FROM VENTAS;
SET SQL_SAFE_UPDATES = 0;
UPDATE VENTAS SET Tipo_Producto = 'Vestidos' WHERE Cod_Producto LIKE '7%';
SELECT * FROM VENTAS;
UPDATE VENTAS SET Tipo_Producto = 'Zapatos' WHERE Cod_Producto LIKE '8%';
SELECT * FROM VENTAS;
UPDATE VENTAS SET Tipo_Producto = 'corbatas' WHERE Cod_Producto LIKE '9%';
SELECT * FROM VENTAS;
SELECT COUNT(*) AS TotalRegistros FROM VENTAS;
SELECT Id_ventas, Cod_Producto, Cantidad, Valor_Venta FROM VENTAS WHERE Cantidad > 10 OR Valor_Venta > 10000;
SELECT * FROM VENTAS WHERE NOT Cod_Producto = 7501;
SELECT Tipo_Producto, SUM(Valor_Venta) AS SumaTotalVentas, AVG(Valor_Venta) AS PromedioVentas FROM VENTAS GROUP BY Tipo_Producto;
SELECT * FROM VENTAS ORDER BY Valor_Venta DESC LIMIT 1;
SELECT * FROM VENTAS ORDER BY Valor_Venta ASC LIMIT 1;
SELECT Tipo_Producto, COUNT(Id_ventas) AS CantidadVentas FROM VENTAS GROUP BY Tipo_Producto;
SELECT * FROM VENTAS ORDER BY Valor_Venta DESC;
SELECT DISTINCT Tipo_Producto FROM VENTAS;
SELECT Tipo_Producto, SUM(Cantidad) AS TotalArticulosVendidos FROM VENTAS GROUP BY Tipo_Producto;
DELETE FROM VENTAS WHERE Cod_Producto = 9801;
SELECT * FROM VENTAS;